### ISSUE TITLE
Core mechanics have changed

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/item_drop#8]
- The mod no longer drops items on the node below the newly dug node, but now throws items off to the sides with great velocity, 2-6 nodes away. 

- The pickup feature no longer picks items up that are in range but at player waist level (1 node up)

- The key-triggered pickup lags more than before.

- Pickup sound plays multiple times even for one item picked up

This changes core behavior of the mod and is likely to upset players and server owners who depend on the functionality to work a certain way. I need to put the newer commits into a new branch now that it's clear they're not fit for production yet. All contributions are appreciatiated, they just need testing before going into `master` and some of these commits are clearly not tested enough.

I've reverted `master` to 962d0a3889db609c349e3e99a58104bbb22f4c93 and put newer commits in `rewrite`. `master` is protected to allow for due process with PRs instead of direct pushing, while `rewrite` is open as usual (@HybridDog). Additionally I plan to create a new `dev` branch for vetted and tested new commits.
<details>

```
git checkout -b newbranch # switch to a new branch
git branch -f master 962d0a3889db609c349e3e99a58104bbb22f4c93 # make master point to some older commit 
```
</details>

**Comment by HybridDog** [comment]
Thanks for testing. l'll push a few fixes to rewrite if l find the bugs.

> The mod no longer drops items on the node below the newly dug node, but now throws items off to the sides with great velocity, 2-6 nodes away.

l accidentally set it to z instead of 1/z: https://github.com/minetest-mods/item_drop/commit/271a5778816c0e4bbd7deca8f01de093b0e8be51?w=1#diff-d7d74284e2e39f6c06d199c8e2bedbd0L248
l've fixed it in rewrite.

> The pickup feature no longer picks items up that are in range but at player waist level (1 node up)

The position where the objects are searched is the same:
https://github.com/minetest-mods/item_drop/blob/master/init.lua#L42
https://github.com/minetest-mods/item_drop/blob/rewrite/init.lua#L135
l can't reproduce your problem, items are still picked when they're next to the feet. You used the default settings, didn't you?

> The key-triggered pickup lags more than before.

l can't reproduce it, can you be more precise?
When dropping an item there's a delay until the player is able to pick it up again (see the README). l could disable this delay if pickup_key is enabled and pickup_keyinvert is disabled.

> Pickup sound plays multiple times even for one item picked up

Did you use the newest minetest version?
(Recently there was a fix which makes minetest.get_objects_inside_radius not return removed objects. l guess l can disable playing the sound multiple times in old minetest versions if l know the bug.)
Which mods and item_drop settings did you use?

**Comment by tacotexmex** [comment]
271a577 indeed solved the problem of velocity. Great that it was so easily solved. 👍 

> l can't reproduce your problem, items are still picked when they're next to the feet. You used the default settings, didn't you?

Yes, default settings. I wonder, is the base of the radius (`pos.y+0.5`) derived from player waist, player feet or other? Because what I meant was that items at waist level didn't get picked even though they were directly adjacent to the player. A bigger radius setting solved that however. 👍 

>l can't reproduce it, can you be more precise?
> When dropping an item there's a delay until the player is able to pick it up again (see the README). l could disable this delay if pickup_key is enabled and pickup_keyinvert is disabled.

Sorry for not investigating enough myself first. You're right. What I perceived as lag must've been the item age feature at work. I think your suggestion of "disable this delay if pickup_key is enabled" is a good solution, since it's not needed. 👍 

> Did you use the newest minetest version?
(Recently there was a fix which makes minetest.get_objects_inside_radius not return removed objects. l guess l can disable playing the sound multiple times in old minetest versions if l know the bug.)
Which mods and item_drop settings did you use?

With the latest commits I can't seem to reproduce the sound bug at all (with default mod settings as last time). In both instances I've been using .4.16 (stable). So it seems solved by itself, magic or other. 👍 

Thank you for your work.

**Comment by HybridDog** [comment]
> A bigger radius setting solved that however.

You could use the collisionbox of the player to test whether items are nearby.
 
> I think your suggestion of "disable this delay if pickup_key is enabled" is a good solution, since it's not needed.

l did a commit. Now when holding the keys, you may hear that the delay is lowered automatically when an item was collected shortly before.

**Comment by HybridDog** [comment]
l don't want to open 36 pull requests

**Comment by tacotexmex** [comment]
No need. When `rewrite` is ready, we'll just merge the whole branch back into `master`.
